// src/components/Contact.vue
<template>
<section id="contact" class="py-32 bg-gray-50 dark:bg-[#111] relative overflow-hidden transition-colors">
    <div style="position:absolute;bottom:0;right:0;width:400px;height:400px;border-radius:50%;border:1px solid var(--grid-line);animation:pulseRing 8s ease-in-out infinite;transform-origin:bottom right;"></div>
    <div style="position:absolute;top:10%;left:-100px;width:250px;height:250px;border:1px solid var(--grid-line);animation:rotateSq 25s linear infinite;"></div>

    <div class="max-w-7xl mx-auto px-6 relative z-10 grid lg:grid-cols-2 gap-16">
        <div class="reveal delay-1">
            <span class="text-xs font-bold uppercase tracking-widest text-gray-400">04 — Contact</span>
            <h2 class="text-4xl md:text-6xl font-black text-black dark:text-white tracking-tighter mt-4 mb-8 transition-colors">Let's work<br>together.</h2>
            <p class="text-gray-500 dark:text-gray-400 mb-12 max-w-md text-lg font-light leading-relaxed transition-colors">
                Currently open for full-time job opportunities. Feel free to reach out to discuss how I can contribute to your next project.
            </p>

            <div class="space-y-6">
                <div class="flex items-center gap-4">
                    <div class="w-10 h-10 bg-black dark:bg-white flex items-center justify-center text-white dark:text-black transition-colors">
                        <i class="fa-solid fa-at text-xl"></i>
                    </div>
                    <div>
                        <span class="block text-xs font-bold uppercase tracking-widest text-gray-400 mb-0.5">Email</span>
                        <a href="mailto:hassanraza03097477849@gmail.com" class="text-base font-semibold text-black dark:text-white hover:text-gray-500 dark:hover:text-gray-400 transition-colors anim-link">hassanraza03097477849@gmail.com</a>
                    </div>
                </div>
                <div class="flex items-center gap-4">
                    <div class="w-10 h-10 bg-gray-200 dark:bg-zinc-800 flex items-center justify-center transition-colors">
                        <i class="fa-solid fa-location-dot text-black dark:text-white text-xl transition-colors"></i>
                    </div>
                    <div>
                        <span class="block text-xs font-bold uppercase tracking-widest text-gray-400 mb-0.5">Location</span>
                        <span class="text-base font-semibold text-black dark:text-white transition-colors">Karachi, Pakistan</span>
                    </div>
                </div>
                <div class="flex items-center gap-4">
                    <div class="w-10 h-10 bg-gray-200 dark:bg-zinc-800 flex items-center justify-center transition-colors">
                        <i class="fa-solid fa-file-lines text-black dark:text-white text-xl transition-colors"></i>
                    </div>
                    <div>
                        <span class="block text-xs font-bold uppercase tracking-widest text-gray-400 mb-0.5">Resume</span>
                        <a href="/2132.pdf" download class="text-base font-semibold text-black dark:text-white hover:text-gray-500 dark:hover:text-gray-400 transition-colors anim-link">Download CV</a>
                    </div>
                </div>
                <div class="flex items-center gap-4">
                    <div class="w-10 h-10 bg-gray-200 dark:bg-zinc-800 flex items-center justify-center transition-colors">
                        <i class="fa-solid fa-phone text-black dark:text-white text-xl transition-colors"></i>
                    </div>
                    <div>
                        <span class="block text-xs font-bold uppercase tracking-widest text-gray-400 mb-0.5">Phone</span>
                        <span class="text-base font-semibold text-black dark:text-white transition-colors">0309-7477849</span>
                    </div>
                </div>
            </div>
        </div>

        <div class="reveal delay-3">
            <div class="bg-white dark:bg-zinc-900 border border-gray-200 dark:border-zinc-800 shadow-sm p-8 lg:p-10 transition-colors" id="form-container">
                <form v-if="!formSubmitted" @submit.prevent="submitForm" class="w-full">
                    <div class="grid grid-cols-2 gap-6 mb-8">
                        <div class="space-y-2">
                            <label class="text-xs font-bold uppercase tracking-widest text-gray-500 dark:text-gray-400">Name</label>
                            <input v-model="form.name" type="text" required class="form-input placeholder-gray-400 dark:placeholder-gray-600" placeholder="John Doe">
                        </div>
                        <div class="space-y-2">
                            <label class="text-xs font-bold uppercase tracking-widest text-gray-500 dark:text-gray-400">Email</label>
                            <input v-model="form.email" type="email" required class="form-input placeholder-gray-400 dark:placeholder-gray-600" placeholder="john@example.com">
                        </div>
                    </div>
                    
                    <div class="space-y-2 mb-8">
                        <label class="text-xs font-bold uppercase tracking-widest text-gray-500 dark:text-gray-400">Inquiry type</label>
                        <select v-model="form.inquiry_type" required class="form-input">
                            <option value="Full-Time Opportunity" class="dark:bg-zinc-900">Full-Time Opportunity</option>
                            <option value="Freelance / Contract" class="dark:bg-zinc-900">Freelance / Contract</option>
                            <option value="Consulting" class="dark:bg-zinc-900">Consulting</option>
                            <option value="Other" class="dark:bg-zinc-900">Other</option>
                        </select>
                    </div>
                    
                    <div class="space-y-2 mb-8">
                        <label class="text-xs font-bold uppercase tracking-widest text-gray-500 dark:text-gray-400">Message</label>
                        <textarea v-model="form.message" rows="4" required class="form-input resize-none placeholder-gray-400 dark:placeholder-gray-600" placeholder="Tell me about your project or opportunity..."></textarea>
                    </div>
                    
                    <button type="submit" :disabled="loading" class="w-full bg-black dark:bg-white text-white dark:text-black py-4 text-xs font-black uppercase tracking-widest hover:bg-gray-800 dark:hover:bg-gray-200 transition-colors relative overflow-hidden group border-none cursor-pointer">
                        <span class="relative z-10 mix-blend-difference text-white">{{ btnText }}</span>
                        <div class="absolute inset-0 bg-gray-800 dark:bg-gray-300 translate-x-full group-hover:translate-x-0 transition-transform duration-500 ease-out"></div>
                    </button>
                </form>

                <div v-else class="text-center py-12 reveal visible">
                    <i class="fa-solid fa-circle-check text-5xl text-[#0D7961] mb-6"></i>
                    <h3 class="text-3xl font-black text-black dark:text-white tracking-tighter mb-4">Message Sent!</h3>
                    <p class="text-gray-500 dark:text-gray-400 text-lg leading-relaxed">
                        Thank you for reaching out. I've received your message and will respond to you shortly.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
</template>

<script setup>
import { ref, reactive } from 'vue';

const formSubmitted = ref(false);
const loading = ref(false);
const btnText = ref('Send Message →');

const form = reactive({
    name: '',
    email: '',
    inquiry_type: 'Full-Time Opportunity',
    message: '',
    _subject: 'New Inquiry via Portfolio',
    _template: 'box'
});

const submitForm = async () => {
    loading.value = true;
    btnText.value = 'Sending...';

    try {
        const response = await fetch("https://formsubmit.co/ajax/hassanraza03097477849@gmail.com", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            body: JSON.stringify(form)
        });
        
        if (response.ok) {
            formSubmitted.value = true;
        } else {
            throw new Error('Error sending message');
        }
    } catch (error) {
        btnText.value = 'Error! Try Again.';
        setTimeout(() => {
            btnText.value = 'Send Message →';
            loading.value = false;
        }, 3000);
    }
};
</script>

// src/components/Contact.tsx
"use client";

import { useState } from "react";
import { db } from "@/lib/firebase/client";
import { collection, addDoc, serverTimestamp } from "firebase/firestore";

export default function Contact() {
  const [formSubmitted, setFormSubmitted] = useState(false);
  const [loading, setLoading] = useState(false);
  const [btnText, setBtnText] = useState("Send Message →");

  const [form, setForm] = useState({
    name: "",
    email: "",
    company: "",
    role: "",
    inquiry_type: "Full-Time Opportunity",
    message: "",
    _subject: "New Job Opportunity / Inquiry via Portfolio",
    _template: "box",
  });

  const submitForm = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setBtnText("Sending...");

    try {
      await addDoc(collection(db, "leads"), {
        ...form,
        createdAt: serverTimestamp(),
        status: "new",
      });
      
      setFormSubmitted(true);
    } catch (err) {
      setBtnText("Error! Try Again.");
      setTimeout(() => {
        setBtnText("Send Message →");
        setLoading(false);
      }, 3000);
    }
  };

  const handleChange = (
    e: React.ChangeEvent<
      HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement
    >
  ) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  return (
    <section
      id="contact"
      className="py-20 bg-white dark:bg-[#0a0a0a] relative transition-colors"
    >
      <div className="max-w-7xl mx-auto px-6 relative z-10 grid lg:grid-cols-2 gap-16 lg:gap-24 items-start">
        
        {/* Left Column - Details */}
        <div className="reveal delay-1 sticky top-32">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            <div className="p-6 border border-gray-200 dark:border-zinc-800 bg-gray-50 dark:bg-[#111] transition-colors">
              <i className="fa-solid fa-at text-black dark:text-white mb-4 text-xl"></i>
              <span className="block text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-1">
                Email
              </span>
              <a
                href="mailto:hassanraza03097477849@gmail.com"
                className="text-sm font-bold text-black dark:text-white hover:text-gray-500 transition-colors break-all"
              >
                hassanraza03097477849<br/>@gmail.com
              </a>
            </div>

            <div className="p-6 border border-gray-200 dark:border-zinc-800 bg-gray-50 dark:bg-[#111] transition-colors">
              <i className="fa-solid fa-location-dot text-black dark:text-white mb-4 text-xl"></i>
              <span className="block text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-1">
                Location
              </span>
              <span className="text-sm font-bold text-black dark:text-white transition-colors block">
                Karachi, Pakistan
                <span className="block text-gray-400 font-normal mt-1">(Open to Relocation)</span>
              </span>
            </div>

            <div className="p-6 border border-gray-200 dark:border-zinc-800 bg-gray-50 dark:bg-[#111] transition-colors">
              <i className="fa-solid fa-phone text-black dark:text-white mb-4 text-xl"></i>
              <span className="block text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-1">
                Phone
              </span>
              <span className="text-sm font-bold text-black dark:text-white transition-colors">
                0309-7477849
              </span>
            </div>

            <div className="p-6 border border-black dark:border-white bg-black dark:bg-white transition-colors group">
              <i className="fa-solid fa-file-lines text-white dark:text-black mb-4 text-xl transition-colors"></i>
              <span className="block text-[10px] font-bold uppercase tracking-widest text-gray-400 dark:text-gray-500 mb-1">
                Resume
              </span>
              <a
                href="/api/cv/generate"
                target="_blank"
                className="text-sm font-black text-white dark:text-black flex items-center gap-2 group-hover:gap-4 transition-all"
              >
                Download CV <i className="fa-solid fa-arrow-down"></i>
              </a>
            </div>
          </div>
        </div>

        {/* Right Column - Form */}
        <div className="reveal delay-3">
          <div className="bg-white dark:bg-[#0a0a0a] border border-gray-200 dark:border-zinc-800 p-8 lg:p-12 transition-colors">
            {!formSubmitted ? (
              <form onSubmit={submitForm} className="w-full">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                  <div className="space-y-2">
                    <label className="text-[10px] font-bold uppercase tracking-widest text-black dark:text-white">
                      Your Name <span className="text-red-500">*</span>
                    </label>
                    <input
                      name="name"
                      value={form.name}
                      onChange={handleChange}
                      type="text"
                      required
                      className="w-full bg-gray-50 dark:bg-[#111] border border-gray-200 dark:border-zinc-800 text-black dark:text-white px-4 py-3 text-sm focus:outline-none focus:border-black dark:focus:border-white transition-colors placeholder-gray-400 dark:placeholder-gray-600"
                      placeholder="John Doe"
                    />
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] font-bold uppercase tracking-widest text-black dark:text-white">
                      Work Email <span className="text-red-500">*</span>
                    </label>
                    <input
                      name="email"
                      value={form.email}
                      onChange={handleChange}
                      type="email"
                      required
                      className="w-full bg-gray-50 dark:bg-[#111] border border-gray-200 dark:border-zinc-800 text-black dark:text-white px-4 py-3 text-sm focus:outline-none focus:border-black dark:focus:border-white transition-colors placeholder-gray-400 dark:placeholder-gray-600"
                      placeholder="john@company.com"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                  <div className="space-y-2">
                    <label className="text-[10px] font-bold uppercase tracking-widest text-black dark:text-white">
                      Company Name
                    </label>
                    <input
                      name="company"
                      value={form.company}
                      onChange={handleChange}
                      type="text"
                      className="w-full bg-gray-50 dark:bg-[#111] border border-gray-200 dark:border-zinc-800 text-black dark:text-white px-4 py-3 text-sm focus:outline-none focus:border-black dark:focus:border-white transition-colors placeholder-gray-400 dark:placeholder-gray-600"
                      placeholder="Acme Corp"
                    />
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] font-bold uppercase tracking-widest text-black dark:text-white">
                      Role / Position
                    </label>
                    <input
                      name="role"
                      value={form.role}
                      onChange={handleChange}
                      type="text"
                      className="w-full bg-gray-50 dark:bg-[#111] border border-gray-200 dark:border-zinc-800 text-black dark:text-white px-4 py-3 text-sm focus:outline-none focus:border-black dark:focus:border-white transition-colors placeholder-gray-400 dark:placeholder-gray-600"
                      placeholder="e.g. Senior Frontend Engineer"
                    />
                  </div>
                </div>

                <div className="space-y-2 mb-6">
                  <label className="text-[10px] font-bold uppercase tracking-widest text-black dark:text-white">
                    Inquiry Type <span className="text-red-500">*</span>
                  </label>
                  <select
                    name="inquiry_type"
                    value={form.inquiry_type}
                    onChange={handleChange}
                    required
                    className="w-full bg-gray-50 dark:bg-[#111] border border-gray-200 dark:border-zinc-800 text-black dark:text-white px-4 py-3 text-sm focus:outline-none focus:border-black dark:focus:border-white transition-colors"
                  >
                    <option value="Full-Time Opportunity">Full-Time Opportunity</option>
                    <option value="Freelance / Contract">Freelance / Contract</option>
                    <option value="Consulting">Consulting</option>
                    <option value="Other">Other</option>
                  </select>
                </div>

                <div className="space-y-2 mb-8">
                  <label className="text-[10px] font-bold uppercase tracking-widest text-black dark:text-white">
                    Message Details <span className="text-red-500">*</span>
                  </label>
                  <textarea
                    name="message"
                    value={form.message}
                    onChange={handleChange}
                    rows={4}
                    required
                    className="w-full bg-gray-50 dark:bg-[#111] border border-gray-200 dark:border-zinc-800 text-black dark:text-white px-4 py-3 text-sm focus:outline-none focus:border-black dark:focus:border-white transition-colors placeholder-gray-400 dark:placeholder-gray-600 resize-none"
                    placeholder="Tell me about the role, tech stack, or opportunity..."
                  ></textarea>
                </div>

                <button
                  type="submit"
                  disabled={loading}
                  className="w-full bg-black dark:bg-white text-white dark:text-black py-4 text-xs font-black uppercase tracking-widest hover:bg-gray-800 dark:hover:bg-gray-200 transition-colors cursor-pointer"
                >
                  {btnText}
                </button>
              </form>
            ) : (
              <div className="text-center py-16">
                <i className="fa-solid fa-circle-check text-5xl text-black dark:text-white mb-6"></i>
                <h3 className="text-3xl font-black text-black dark:text-white tracking-tighter mb-4">
                  Transmission Sent.
                </h3>
                <p className="text-gray-500 dark:text-gray-400 text-sm leading-relaxed">
                  Thank you for reaching out. I have received your message and will process it shortly.
                </p>
              </div>
            )}
          </div>
        </div>

      </div>
    </section>
  );
}
