// _old_vue/src/components/Navbar.vue
<template>
<nav class="fixed w-full border-b border-gray-200 dark:border-zinc-800 bg-white/80 dark:bg-[#0a0a0a]/80 backdrop-blur-lg z-50 transition-colors duration-300">
    <div class="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
        <div class="flex items-center gap-3">
            <div class="w-8 h-8 bg-black dark:bg-white flex items-center justify-center transition-colors">
                <span class="text-white dark:text-black font-black text-xs transition-colors">HR</span>
            </div>
            <span class="font-black tracking-widest uppercase text-sm dark:text-white transition-colors">Hassan Raza</span>
        </div>
        <div class="hidden md:flex items-center space-x-8 text-xs font-bold uppercase tracking-widest">
            <a href="#about" :class="navClass('#about')" @click="active = '#about'" class="hover:text-black dark:hover:text-white transition-colors anim-link">About</a>
            <a href="#expertise" :class="navClass('#expertise')" @click="active = '#expertise'" class="hover:text-black dark:hover:text-white transition-colors anim-link">Stack</a>
            <a href="#capabilities" :class="navClass('#capabilities')" @click="active = '#capabilities'" class="hover:text-black dark:hover:text-white transition-colors anim-link">Services</a>
            
            <button @click="$emit('toggle-theme')" class="text-gray-500 hover:text-black dark:text-gray-400 dark:hover:text-white transition-colors outline-none" aria-label="Toggle Dark Mode">
                <i v-if="!isDark" class="fa-solid fa-moon text-lg"></i>
                <i v-else class="fa-solid fa-sun text-lg"></i>
            </button>

            <a href="#contact" class="bg-black dark:bg-white text-white dark:text-black px-5 py-2 hover:bg-gray-800 dark:hover:bg-gray-200 transition-colors">Contact</a>
        </div>
        <div class="flex items-center gap-4 md:hidden">
            <button @click="$emit('toggle-theme')" class="text-gray-500 dark:text-gray-400 outline-none">
                <i v-if="!isDark" class="fa-solid fa-moon text-lg"></i>
                <i v-else class="fa-solid fa-sun text-lg"></i>
            </button>
            <a href="#contact" class="text-xs font-bold uppercase tracking-widest text-black dark:text-white border border-black dark:border-white px-3 py-2 transition-colors">Contact</a>
        </div>
    </div>
</nav>
</template>

<script setup>
import { ref } from 'vue';

defineProps({
    isDark: Boolean
});

const active = ref('');
const navClass = (path) => {
    return active.value === path ? 'text-black dark:text-white' : 'text-gray-500 dark:text-gray-400';
};
</script>

// src/components/Navbar.tsx
"use client";

import { useEffect, useState } from "react";
import { Moon, Sun } from "lucide-react";
import Link from "next/link";

export default function Navbar() {
  const [isDark, setIsDark] = useState(false);
  const [active, setActive] = useState("");
  const [isVisible, setIsVisible] = useState(true);
  const [lastScrollY, setLastScrollY] = useState(0);

  useEffect(() => {
    if (typeof window !== "undefined") {
      // Theme logic
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setIsDark(document.documentElement.classList.contains("dark"));
      const observer = new MutationObserver(() => {
        setIsDark(document.documentElement.classList.contains("dark"));
      });
      observer.observe(document.documentElement, {
        attributes: true,
        attributeFilter: ["class"],
      });

      // Scroll direction logic
      const handleScroll = () => {
        const currentScrollY = window.scrollY;
        
        // Hide on scroll down, show on scroll up
        if (currentScrollY > lastScrollY && currentScrollY > 100) {
          setIsVisible(false);
        } else {
          setIsVisible(true);
        }
        
        setLastScrollY(currentScrollY);
      };

      window.addEventListener("scroll", handleScroll, { passive: true });

      return () => {
        observer.disconnect();
        window.removeEventListener("scroll", handleScroll);
      };
    }
  }, [lastScrollY]);

  const toggleTheme = () => {
    const newIsDark = !isDark;
    setIsDark(newIsDark);
    if (newIsDark) {
      document.documentElement.classList.add("dark");
      localStorage.setItem("theme", "dark");
    } else {
      document.documentElement.classList.remove("dark");
      localStorage.setItem("theme", "light");
    }
  };

  const navClass = (path: string) => {
    return active === path
      ? "text-black dark:text-white"
      : "text-gray-500 dark:text-gray-400";
  };

  return (
    <nav 
      className={`fixed top-0 left-0 right-0 w-full bg-white dark:bg-[#0a0a0a] border-b border-gray-200 dark:border-zinc-900 z-50 transition-all duration-300 ${
        isVisible ? "translate-y-0" : "-translate-y-full"
      }`}
    >
      <div className="max-w-7xl mx-auto px-6 h-20 flex justify-between items-center">
        
        {/* Logo */}
        <Link href="/" className="flex items-center gap-4 group">
          <div className="w-10 h-10 bg-black dark:bg-white flex items-center justify-center transition-transform duration-500">
            <span className="text-white dark:text-black font-black text-sm leading-none">
              HR
            </span>
          </div>
          <span className="font-black tracking-widest uppercase text-sm text-black dark:text-white">
            Hassan Raza
          </span>
        </Link>

        {/* Desktop Links */}
        <div className="hidden md:flex items-center gap-10">
          <div className="flex items-center gap-8 text-xs font-bold uppercase tracking-widest">
            <Link
              href="/#about"
              className={`${navClass("#about")} hover:text-black dark:hover:text-white transition-colors anim-link`}
              onClick={() => setActive("#about")}
            >
              About
            </Link>
            <Link
              href="/#expertise"
              className={`${navClass("#expertise")} hover:text-black dark:hover:text-white transition-colors anim-link`}
              onClick={() => setActive("#expertise")}
            >
              Stack
            </Link>
            <Link
              href="/#capabilities"
              className={`${navClass("#capabilities")} hover:text-black dark:hover:text-white transition-colors anim-link`}
              onClick={() => setActive("#capabilities")}
            >
              Value
            </Link>
            <Link
              href="/#projects"
              className={`${navClass("#projects")} hover:text-black dark:hover:text-white transition-colors anim-link`}
              onClick={() => setActive("#projects")}
            >
              Work
            </Link>
          </div>

          <div className="flex items-center gap-6">
            <button
              onClick={toggleTheme}
              className="text-gray-500 hover:text-black dark:text-gray-400 dark:hover:text-white transition-colors outline-none"
              aria-label="Toggle Dark Mode"
            >
              {!isDark ? <Moon size={18} /> : <Sun size={18} />}
            </button>

            <Link
              href="/#contact"
              className="bg-black dark:bg-white text-white dark:text-black px-8 py-3 text-[10px] font-black uppercase tracking-widest hover:bg-gray-800 dark:hover:bg-gray-200 transition-colors"
            >
              Hire Me
            </Link>
          </div>
        </div>

        {/* Mobile Actions */}
        <div className="flex items-center gap-4 md:hidden">
          <button
            onClick={toggleTheme}
            className="text-gray-500 hover:text-black dark:text-gray-400 dark:hover:text-white outline-none"
          >
            {!isDark ? <Moon size={18} /> : <Sun size={18} />}
          </button>
          <Link
            href="/#contact"
            className="bg-black dark:bg-white text-white dark:text-black px-4 py-2 text-[10px] font-black uppercase tracking-widest"
          >
            Contact
          </Link>
        </div>
        
      </div>
    </nav>
  );
}
