// src/components/Services.vue
<template>
<section id="capabilities" class="py-32 bg-white dark:bg-[#0a0a0a] border-b border-gray-200 dark:border-zinc-900 relative overflow-hidden transition-colors">
    <div class="absolute right-0 top-1/2 -translate-y-1/2 text-[20vw] font-black text-gray-50 dark:text-zinc-900 select-none pointer-events-none leading-none transition-colors">03</div>

    <div class="max-w-7xl mx-auto px-6 relative z-10">
        <div class="flex flex-col md:flex-row justify-between items-end mb-20">
            <div class="reveal">
                <span class="text-xs font-bold uppercase tracking-widest text-gray-400">03 — Value</span>
                <h2 class="text-4xl md:text-5xl font-black text-black dark:text-white tracking-tighter mt-4 transition-colors">Value I Bring<br>To Your Team</h2>
            </div>
            <p class="text-gray-500 dark:text-gray-400 max-w-sm text-sm mt-6 md:mt-0 reveal delay-2 transition-colors">Deep technical experience delivering high-impact, scalable solutions for businesses.</p>
        </div>

        <div class="grid lg:grid-cols-3 gap-8">
            <div class="cap-card border border-gray-200 dark:border-zinc-800 dark:bg-zinc-900 p-10 reveal delay-1">
                <div class="card-content">
                    <div class="card-num text-5xl font-black mb-8 leading-none dark:text-zinc-600">01</div>
                    <h3 class="card-title text-2xl font-black mb-4">ERP &amp; Systems Architecture</h3>
                    <p class="card-body text-sm leading-relaxed dark:text-gray-400">
                        End-to-end development of comprehensive Enterprise Resource Planning systems — complex financial accounting integrations, automated workflows, custom billing engines, and multi-module business platforms.
                    </p>
                    <div class="mt-8 flex flex-wrap gap-2">
                        <span class="text-xs border border-current px-2 py-1 font-bold uppercase tracking-wider card-body dark:text-gray-400">Laravel</span>
                        <span class="text-xs border border-current px-2 py-1 font-bold uppercase tracking-wider card-body dark:text-gray-400">MySQL</span>
                        <span class="text-xs border border-current px-2 py-1 font-bold uppercase tracking-wider card-body dark:text-gray-400">Vue.js</span>
                    </div>
                </div>
            </div>

            <div class="cap-card border border-gray-200 dark:border-zinc-800 dark:bg-zinc-900 p-10 reveal delay-2">
                <div class="card-content">
                    <div class="card-num text-5xl font-black mb-8 leading-none dark:text-zinc-600">02</div>
                    <h3 class="card-title text-2xl font-black mb-4">High-Density Dashboards</h3>
                    <p class="card-body text-sm leading-relaxed dark:text-gray-400">
                        Designing and building punchy, one-screen digital environments. Maximising data visibility while maintaining a sleek, intuitive UI that eliminates scroll fatigue — every pixel earns its place.
                    </p>
                    <div class="mt-8 flex flex-wrap gap-2">
                        <span class="text-xs border border-current px-2 py-1 font-bold uppercase tracking-wider card-body dark:text-gray-400">React</span>
                        <span class="text-xs border border-current px-2 py-1 font-bold uppercase tracking-wider card-body dark:text-gray-400">Figma</span>
                        <span class="text-xs border border-current px-2 py-1 font-bold uppercase tracking-wider card-body dark:text-gray-400">Tailwind</span>
                    </div>
                </div>
            </div>

            <div class="cap-card border border-gray-200 dark:border-zinc-800 dark:bg-zinc-900 p-10 reveal delay-3">
                <div class="card-content">
                    <div class="card-num text-5xl font-black mb-8 leading-none dark:text-zinc-600">03</div>
                    <h3 class="card-title text-2xl font-black mb-4">Complex Database Logic</h3>
                    <p class="card-body text-sm leading-relaxed dark:text-gray-400">
                        Structuring scalable database logic using advanced joins, indexes, and optimised queries. Fast, reliable data retrieval for massive datasets, valuations, and intelligence reports.
                    </p>
                    <div class="mt-8 flex flex-wrap gap-2">
                        <span class="text-xs border border-current px-2 py-1 font-bold uppercase tracking-wider card-body dark:text-gray-400">MySQL</span>
                        <span class="text-xs border border-current px-2 py-1 font-bold uppercase tracking-wider card-body dark:text-gray-400">MongoDB</span>
                        <span class="text-xs border border-current px-2 py-1 font-bold uppercase tracking-wider card-body dark:text-gray-400">REST APIs</span>
                    </div>
                </div>
            </div>
        </div>

        <div class="mt-24 grid md:grid-cols-2 gap-12 border-t border-gray-200 dark:border-zinc-800 pt-16 reveal delay-4 transition-colors">
            <div class="flex gap-6 items-start">
                <div class="w-12 h-12 bg-black dark:bg-white flex items-center justify-center flex-shrink-0 transition-colors">
                    <i class="fa-solid fa-building text-white dark:text-black text-2xl transition-colors"></i>
                </div>
                <div>
                    <p class="font-black text-lg text-black dark:text-white transition-colors">Software Engineering Education</p>
                    <p class="text-gray-400 font-bold text-sm">Aptech Garden &amp; Lyari Degree College</p>
                    <p class="text-sm text-gray-500 dark:text-gray-400 mt-2 leading-relaxed transition-colors">Currently pursuing Diploma in Software Development and previously completed Intermediate in Pre-Engineering, building a strong analytical and programming foundation.</p>
                </div>
            </div>
            <div class="flex gap-6 items-start">
                <div class="w-12 h-12 bg-gray-100 dark:bg-zinc-800 flex items-center justify-center flex-shrink-0 transition-colors">
                    <i class="fa-solid fa-chart-simple text-black dark:text-white text-2xl transition-colors"></i>
                </div>
                <div>
                    <p class="font-black text-lg text-black dark:text-white transition-colors">Operations &amp; Administration</p>
                    <p class="text-gray-400 font-bold text-sm">Al-Azhar School &amp; Nafey Traders</p>
                    <p class="text-sm text-gray-500 dark:text-gray-400 mt-2 leading-relaxed transition-colors">Hands-on experience with POS systems, proactive inventory management, and detailed administrative record keeping.</p>
                </div>
            </div>
        </div>
    </div>
</section>
</template>

<script setup>
</script>

// src/components/Services.tsx
export default function Services() {
  const capabilities = [
    {
      num: "01",
      title: "ERP & Systems Architecture",
      desc: "End-to-end development of comprehensive Enterprise Resource Planning systems — complex financial accounting integrations, automated workflows, custom billing engines, and multi-module business platforms.",
      tags: ["Laravel", "MySQL", "Vue.js"]
    },
    {
      num: "02",
      title: "High-Density Dashboards",
      desc: "Designing and building punchy, one-screen digital environments. Maximising data visibility while maintaining a sleek, intuitive UI that eliminates scroll fatigue — every pixel earns its place.",
      tags: ["React", "Figma", "Tailwind"]
    },
    {
      num: "03",
      title: "Complex Database Logic",
      desc: "Structuring scalable database logic using advanced joins, indexes, and optimised queries. Fast, reliable data retrieval for massive datasets, valuations, and intelligence reports.",
      tags: ["MySQL", "MongoDB", "REST APIs"]
    }
  ];

  return (
    <section
      id="capabilities"
      className="py-20 bg-gray-50 dark:bg-[#111] border-b border-gray-200 dark:border-zinc-900 relative transition-colors"
    >
      <div className="max-w-7xl mx-auto px-6 relative z-10">
        
        {/* Header Layout */}
        <div className="flex flex-col lg:flex-row gap-12 lg:gap-16 items-start mb-16 reveal">
          <div className="lg:w-1/3">
            <div className="flex items-center gap-4 mb-4">
              <span className="w-8 h-px bg-black dark:bg-white transition-colors"></span>
              <span className="text-xs font-bold uppercase tracking-widest text-gray-500 dark:text-gray-400">
                03 — Value
              </span>
            </div>
            <h2 className="text-4xl md:text-6xl font-black text-black dark:text-white tracking-tighter mb-4 transition-colors leading-[1.1]">
              Value
              <br />
              <span className="text-gray-400 dark:text-gray-600">Proposition.</span>
            </h2>
          </div>
          
          <div className="lg:w-2/3 text-xl md:text-2xl font-medium text-black dark:text-white leading-snug">
            Deep technical experience delivering high-impact, scalable solutions. I do not just write code; I engineer business leverage.
          </div>
        </div>

        {/* 3-Column Grid Layout with Watermarks */}
        <div className="grid lg:grid-cols-3 gap-6 reveal delay-1">
          {capabilities.map((cap, index) => (
            <div 
              key={index}
              className="group relative bg-white dark:bg-zinc-900 border border-gray-200 dark:border-zinc-800 p-8 md:p-10 hover:-translate-y-2 hover:shadow-2xl transition-all duration-500 overflow-hidden flex flex-col justify-end min-h-[450px]"
            >
              {/* Massive Number Watermark */}
              <div className="absolute -top-10 -right-6 text-[15rem] font-black text-gray-50 dark:text-zinc-950/30 group-hover:text-gray-100 dark:group-hover:text-zinc-800 transition-colors duration-500 select-none pointer-events-none leading-none z-0">
                {cap.num}
              </div>
              
              <div className="relative z-10 mt-auto">
                <h3 className="text-2xl md:text-3xl font-black text-black dark:text-white mb-4 tracking-tight leading-[1.1]">
                  {cap.title}
                </h3>
                <p className="text-sm text-gray-500 dark:text-gray-400 leading-relaxed mb-8 h-24">
                  {cap.desc}
                </p>
                <div className="flex flex-wrap gap-2">
                  {cap.tags.map((tag) => (
                    <span 
                      key={tag} 
                      className="text-[10px] font-bold uppercase tracking-widest text-black dark:text-white border border-gray-200 dark:border-zinc-700 px-3 py-1.5 bg-white dark:bg-zinc-900"
                    >
                      {tag}
                    </span>
                  ))}
                </div>
              </div>
              
              {/* Top accent line that slides in on hover */}
              <div className="absolute top-0 left-0 w-full h-1 bg-black dark:bg-white scale-x-0 group-hover:scale-x-100 transition-transform duration-500 origin-left z-10"></div>
            </div>
          ))}
        </div>

      </div>
    </section>
  );
}
